@startuml ChaingingState
actor Developer
participant ScriptDirector
participant Mover
participant MoverController

Developer -> ScriptDirector : Writing script
ScriptDirector -> Mover : Changing parameters
Mover -> MoverController : Set Position/Velocity
MoverController -> MoverController : Change Position/Velocity
@enduml

@startuml ErasingSpawnedProcess
actor Developer
participant ScriptDirector
participant Mover
participant Activity
participant MoverController
participant SpriteAnimator

Developer -> ScriptDirector : Writing script
ScriptDirector -> Mover : Erasing/Spawned request
Mover -> Activity : Erase/Spawned
Activity -> MoverController : Disable/Enable
Activity -> SpriteAnimator : Disablie/Enable
@enduml

@startuml TurningInvincible
actor Developer
participant ScriptDirector
participant Mover
participant Invincibility

Developer -> ScriptDirector : Writing script
ScriptDirector -> Mover : Changing parameters
Mover -> Invincibility : Turning invincible
Invincibility -> Invincibility : Decreasing\ninvincible count
@enduml