@startuml GeneratingObject
actor Developer
participant ScriptManager
participant MoverManager
participant Addressenble
participant Mover

Developer -> ScriptManager : Writing scripts
ScriptManager -> MoverManager : Generating request through ID
MoverManager -> Addressenble : Loading
Addressenble --> MoverManager : Prefab
MoverManager -> Mover : Constructing by the prefab
Mover --> MoverManager : Instance
MoverManager --> ScriptManager : Generating response
ScriptManager --> Developer : Game object
Developer --> Developer : Spawning the object
@enduml

@startuml UpdatingObjects
entity UnityEngine
participant GameDirector
participant ScriptManager
participant LuaScript
participant MoverManager
participant Mover

UnityEngine -> GameDirector : Updating
GameDirector -> ScriptManager : Updating
ScriptManager -> LuaScript : Proceeding with the program
LuaScript -> Mover : Changing request for states
GameDirector -> MoverManager : Updating
MoverManager -> Mover : Updating
Mover -> Mover : Changing one's states
@enduml