@startuml GeneratingObject
actor Developer
participant ScriptDirector
participant MoverManager
participant Addressenble
participant Mover

Developer -> ScriptDirector : Writing scripts
ScriptDirector -> MoverManager : Generating request
MoverManager -> Addressenble : Loading
Addressenble --> MoverManager : Prefab
MoverManager -> Mover : Constructing by a prefab
Mover --> MoverManager : Instance
MoverManager --> ScriptDirector : Generating response
ScriptDirector --> Developer : Game object
@enduml